---
  - name: Lilbois docker playbook
    hosts: webservers
    become: true
    tasks:

    - name: Install docker.io (state-present is optional)
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Install python3 (state-present is optional)
      apt:
        name: python3-pip
        state: present

    - name: Install docker python package
      pip:
        name: docker
        state: present

    - name: Create dvwa container
      docker_container:
        name: dvwa_container
        image: cyberxsecurity/dvwa